### ISSUE TITLE
GitLab Support

### ISSUE THREAD

**Issue by hugomd** [egoist/repo-first-commit-api#1]
Would be nice to have to option to specify whether it's a GitLab or GitHub repository, and possible support other providers.

My suggestion would be to add a query parameter to specify a provider, and default to GitHub.

Let me know if you'd like me to make the PR 👍

**Comment by egoist** [comment]
Sure, does gitlab have an API for getting commits? It's even better to support this in https://github.com/egoist/repo-first-commit directly.

**Comment by hugomd** [comment]
@egoist There's an API to [list repository commits](https://docs.gitlab.com/ce/api/commits.html#list-repository-commits) — I'll have a look at it later tonight if I get time, and try adding it to `repo-first-commit` ✌️

**Comment by hugomd** [comment]
@egoist I've just had a decent look into it — looks like the request has to be authenticated to the user who owns the repository in GitLab, even for public repositories. 

I'll close the issue for now until their API opens up.
